services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: local/nginx.dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
      - 443:443
    volumes:
      - ./wordpress_data:/var/www/html:delegated
      - ./opt/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./opt/nginx/localwordpress.conf:/etc/nginx/conf.d/localwordpress.conf
      - ./bin/certs:/etc/nginx/certs/self-signed/
    depends_on:
      - wordpress
    environment:
      VIRTUAL_HOST: ox.docker
      VIRTUAL_PORT: 443
    networks:
      - totoronet

  mariadb:
    container_name: mariadb
    image: mariadb:10.7.1-focal
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      SERVICE_NAME: mariadb
      SERVICE_TAGS: local
      VIRTUAL_HOST: mariadb.docker
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - totoronet

  wordpress:
    container_name: wordpress
    build:
      context: .
      dockerfile: local/wordpress.dockerfile
      args:
        COMPOSER_AUTH: ${COMPOSER_AUTH}
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_ADMIN_USER: admin
      WORDPRESS_ADMIN_PASSWORD: wordpress
      WORDPRESS_ADMIN_EMAIL: "wordpress@ox.docker"
      WP_ENVIRONMENT_TYPE: local
      S3_UPLOADS_USE_LOCAL: "true"
      S3_UPLOADS_USE_INSTANCE_PROFILE: "false"
      S3_UPLOADS_REGION: ""
      S3_UPLOADS_BUCKET: ""
      S3_UPLOADS_KEY: ""
      S3_UPLOADS_SECRET: ""
      SERVER_NAME: "ox.docker"
    volumes:
      - ./wordpress_data:/var/www/html:delegated
    networks:
      - totoronet

volumes:
  mariadb_data:
  wordpress_data:


networks:
  totoronet:
