apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-ms
  namespace: wordpress-ms-prod
  labels:
    app: wordpress-ms
spec:
  replicas: {{ .Values.replicaCount.prod }}
  selector:
    matchLabels:
      app: wordpress-ms
  template:
    metadata:
      labels:
        app: wordpress-ms
    spec:
      containers:
        - name: wordpress
          image: browna2/wordpress-ms:6.7.1-php8.3-fpm-alpine-20250103153709
          ports:
            - containerPort: 9000
          envFrom:
            - secretRef:
                name: wordpress-ms-secrets
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html

        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: wordpress-data
              mountPath: /var/www/html

      volumes:
        - name: wordpress-data
          emptyDir: {}
        - name: nginx-config-volume
          configMap:
            name: nginx-config

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # Max number of pods created above the desired number of replicas
      maxUnavailable: 1  # Max number of pods that can be unavailable during the update

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: wordpress-ms-prod
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.11
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: mariadb-secrets
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
            - name: mariadb-vol-config
              mountPath: /etc/mysql/conf.d/wpms.cnf
              subPath: wpms.cnf

      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-data-pvc
        - name: mariadb-vol-config
          configMap:
            name: mariadb-config
