apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-ms
  namespace: wordpress-ms-prod
  labels:
    app: wordpress-ms
spec:
  replicas: {{ .Values.replicaCount.prod }}
  selector:
    matchLabels:
      app: wordpress-ms
  template:
    metadata:
      labels:
        app: wordpress-ms
    spec:
      containers:
        - name: wordpress
          image: browna2/wordpress-ms:6.9.1-php8.5-fpm-alpine-20260305212342
          ports:
            - containerPort: 9000
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: wordpress-ms-smtp-config
            - secretRef:
                name: wordpress-ms-secrets
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: wordpress-data
              mountPath: /var/www/html
      volumes:
        - name: wordpress-data
          emptyDir: {}
        - name: nginx-config-volume
          configMap:
            name: nginx-config
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
