apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: wordpress-ms-prod
  labels:
    app: wordpress-ms
spec:
  ports:
    - port: 8080
      targetPort: 80
  selector:
    app: wordpress-ms
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: wordpress-ms-prod
  labels:
    app: mariadb
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mariadb
  clusterIP: None