apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-ms-smtp-config
  namespace: wordpress-ms-prod
data:
  SMTP_HOST: {{ .Values.wordpress.extraEnvVars.smtp.host | quote }}
  SMTP_PORT: {{ .Values.wordpress.extraEnvVars.smtp.port | quote }}
  SMTP_AUTH: {{ .Values.wordpress.extraEnvVars.smtp.auth | quote }}
  SMTP_SECURE: {{ .Values.wordpress.extraEnvVars.smtp.secure | quote }}
  SMTP_FROM: {{ .Values.wordpress.extraEnvVars.smtp.from | quote }}
  SMTP_FROM_NAME: {{ .Values.wordpress.extraEnvVars.smtp.fromName | quote }}

