env: "prod"

## @param Manage replica count
##
replicaCount:
  prod: 2

## @param Manage traffic/domains via NGINX ingress
##
ingress:
  enabled: true
  hosts:
    - name: totoro-ox.net
    - name: events.totoro-ox.net